/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.java.project.haneen.gui;

import com.mycompany.java.project.haneen.file.StaffFileHandler;
import com.mycompany.java.project.haneen.file.ParkingEntryFileHandler;
import com.mycompany.java.project.haneen.model.ParkingStaff;
import com.mycompany.java.project.haneen.model.ParkingEntry;
import java.util.ArrayList;

/**
 *
 * @author haneen_almutairi
 */
public class ReportGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReportGUI.class.getName());

    /**
     * Creates new form ReportGUI
     */
    public ReportGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        scrollReport = new javax.swing.JScrollPane();
        txtReport = new javax.swing.JTextArea();
        btnGenerateReport = new javax.swing.JButton();
        btnClearReport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel1.setText("Parking Staff and Security Report");

        txtReport.setEditable(false);
        txtReport.setColumns(20);
        txtReport.setRows(5);
        scrollReport.setViewportView(txtReport);

        btnGenerateReport.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        btnGenerateReport.setText("Generate Report");
        btnGenerateReport.addActionListener(this::btnGenerateReportActionPerformed);

        btnClearReport.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        btnClearReport.setText("Clear");
        btnClearReport.addActionListener(this::btnClearReportActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(scrollReport, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnGenerateReport)
                        .addGap(103, 103, 103)
                        .addComponent(btnClearReport, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(128, 128, 128))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenerateReport)
                    .addComponent(btnClearReport))
                .addGap(34, 34, 34)
                .addComponent(scrollReport, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerateReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateReportActionPerformed
       StaffFileHandler staffFileHandler = new StaffFileHandler();
       ParkingEntryFileHandler entryFileHandler = new ParkingEntryFileHandler();

       ArrayList<ParkingStaff> staffList = staffFileHandler.loadStaff();
       ArrayList<ParkingEntry> entryList = entryFileHandler.loadEntries();

       int totalStaff = staffList.size();
       int onDuty = 0;
       int offDuty = 0;
       int onLeave = 0;

       int currentlyParked = 0;
       int unpaidVehicles = 0;

       for (ParkingStaff staff : staffList) {

          if (staff.getStaffStatus().equalsIgnoreCase("On Duty")) {
             onDuty++;

           }
          
          else if (staff.getStaffStatus().equalsIgnoreCase("Off Duty")) {
             offDuty++;

           }
          
          else if (staff.getStaffStatus().equalsIgnoreCase("On Leave")) {
             onLeave++;
             
           }
    }

        for (ParkingEntry entry : entryList) {

           if (entry.getParkingStatus().equalsIgnoreCase("PARKED")) {
              currentlyParked++;
           }

           if (entry.getPaymentStatus().equalsIgnoreCase("UNPAID")) {
              unpaidVehicles++;
           }
           
}

       String report =
    "                               PARKING STAFF AND SECURITY REPORT\n"
    + "                        =================================\n\n"

    + "STAFF SUMMARY\n"
    + "-------------\n"
    + "Total Staff: " + totalStaff + "\n"
    + "On Duty: " + onDuty + "\n"
    + "Off Duty: " + offDuty + "\n"
    + "On Leave: " + onLeave + "\n\n"

    + "PARKING SUMMARY\n"
    + "---------------\n"
    + "Currently Parked Vehicles: " + currentlyParked + "\n"
    + "Vehicles With Unpaid Parking Fee: " + unpaidVehicles;

       txtReport.setText(report);              
    }//GEN-LAST:event_btnGenerateReportActionPerformed

    private void btnClearReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearReportActionPerformed
       txtReport.setText("");        
       
    }//GEN-LAST:event_btnClearReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ReportGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearReport;
    private javax.swing.JButton btnGenerateReport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane scrollReport;
    private javax.swing.JTextArea txtReport;
    // End of variables declaration//GEN-END:variables
}
