/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.java.project.haneen.gui;
import com.mycompany.java.project.haneen.file.ParkingEntryFileHandler;
import com.mycompany.java.project.haneen.model.ParkingEntry;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author haneen_almutairi
 */
public class StaffSecurityGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StaffSecurityGUI.class.getName());

    /**
     * Creates new form StaffSecurityGUI
     */
    public StaffSecurityGUI() {
    initComponents();

    tblEntries.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);

    tblEntries.getColumnModel().getColumn(1).setPreferredWidth(110); // Vehicle Number
    tblEntries.getColumnModel().getColumn(8).setPreferredWidth(120); // Parking Status
    tblEntries.getColumnModel().getColumn(9).setPreferredWidth(130); // Payment Status

    loadTable();
}
    
    private void loadTable() {

    ParkingEntryFileHandler fileHandler = new ParkingEntryFileHandler();

    ArrayList<ParkingEntry> entryList = fileHandler.loadEntries();

    DefaultTableModel model = (DefaultTableModel) tblEntries.getModel();

    model.setRowCount(0);

    for (ParkingEntry entry : entryList) {

        model.addRow(new Object[]{
            entry.getEntryId(),
            entry.getVehicleNumber(),
            entry.getOwnerName(),
            entry.getSlotId(),
            entry.getEntryDate(),
            entry.getEntryTime(),
            entry.getExitDate(),
            entry.getExitTime(),
            entry.getParkingStatus(),
            entry.getPaymentStatus()
        });
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        scrollEntries = new javax.swing.JScrollPane();
        tblEntries = new javax.swing.JTable();
        btnCurrentlyParked = new javax.swing.JButton();
        btnUnpaidRecords = new javax.swing.JButton();
        btnSearchVehicle = new javax.swing.JButton();
        btnSearchSlot = new javax.swing.JButton();
        btnGenerateReport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Parking Security System");
        setResizable(false);

        lblTitle.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblTitle.setText("Parking Security System");

        tblEntries.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Entry ID", "Vehicle No.", "Owner Name", "Slot ID", "Entry Date", "Entry Time", "Exit Date", "Exit Time", "Parking Status", "Payment Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollEntries.setViewportView(tblEntries);

        btnCurrentlyParked.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        btnCurrentlyParked.setText("Currently Parked");
        btnCurrentlyParked.addActionListener(this::btnCurrentlyParkedActionPerformed);

        btnUnpaidRecords.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        btnUnpaidRecords.setText("Unpaid Records ");
        btnUnpaidRecords.addActionListener(this::btnUnpaidRecordsActionPerformed);

        btnSearchVehicle.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        btnSearchVehicle.setText("Search Vehicle ");
        btnSearchVehicle.addActionListener(this::btnSearchVehicleActionPerformed);

        btnSearchSlot.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        btnSearchSlot.setText("Search Slot");
        btnSearchSlot.addActionListener(this::btnSearchSlotActionPerformed);

        btnGenerateReport.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        btnGenerateReport.setText("Generate Report");
        btnGenerateReport.addActionListener(this::btnGenerateReportActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnCurrentlyParked)
                .addGap(45, 45, 45)
                .addComponent(btnUnpaidRecords)
                .addGap(57, 57, 57)
                .addComponent(btnSearchVehicle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(btnSearchSlot, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btnGenerateReport)
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollEntries))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lblTitle)
                .addGap(30, 30, 30)
                .addComponent(scrollEntries, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCurrentlyParked)
                    .addComponent(btnUnpaidRecords)
                    .addComponent(btnSearchVehicle)
                    .addComponent(btnSearchSlot)
                    .addComponent(btnGenerateReport))
                .addContainerGap(121, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUnpaidRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnpaidRecordsActionPerformed
       ParkingEntryFileHandler fileHandler = new ParkingEntryFileHandler();

       ArrayList<ParkingEntry> entryList = fileHandler.loadEntries();

       DefaultTableModel model = (DefaultTableModel) tblEntries.getModel();

       model.setRowCount(0);

       for (ParkingEntry entry : entryList) {

          if (entry.getPaymentStatus().equalsIgnoreCase("UNPAID")) {

            model.addRow(new Object[]{
            entry.getEntryId(),
            entry.getVehicleNumber(),
            entry.getOwnerName(),
            entry.getSlotId(),
            entry.getEntryDate(),
            entry.getEntryTime(),
            entry.getExitDate(),
            entry.getExitTime(),
            entry.getParkingStatus(),
            entry.getPaymentStatus()
        });

    }
}        
    }//GEN-LAST:event_btnUnpaidRecordsActionPerformed

    private void btnSearchVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchVehicleActionPerformed
       String vehicleNumber = JOptionPane.showInputDialog(this,"Enter Vehicle Number:");
       ParkingEntryFileHandler fileHandler = new ParkingEntryFileHandler();

       ArrayList<ParkingEntry> entryList = fileHandler.loadEntries();

       DefaultTableModel model = (DefaultTableModel) tblEntries.getModel();

       model.setRowCount(0);
       
       boolean found = false;

       for (ParkingEntry entry : entryList) {

          if (entry.getVehicleNumber().equalsIgnoreCase(vehicleNumber)) {

             model.addRow(new Object[]{
             entry.getEntryId(),
             entry.getVehicleNumber(),
             entry.getOwnerName(),
             entry.getSlotId(),
             entry.getEntryDate(),
             entry.getEntryTime(),
             entry.getExitDate(),
             entry.getExitTime(),
             entry.getParkingStatus(),
             entry.getPaymentStatus()
        });

        found = true;
    }
}
     if (!found) {
    JOptionPane.showMessageDialog(this, "Vehicle not found.");
}  
       
    }//GEN-LAST:event_btnSearchVehicleActionPerformed

    private void btnCurrentlyParkedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCurrentlyParkedActionPerformed
        ParkingEntryFileHandler fileHandler = new ParkingEntryFileHandler();

        ArrayList<ParkingEntry> entryList = fileHandler.loadEntries();

        DefaultTableModel model = (DefaultTableModel) tblEntries.getModel();

        model.setRowCount(0);

        for (ParkingEntry entry : entryList) {

           if (entry.getParkingStatus().equalsIgnoreCase("PARKED")) {

              model.addRow(new Object[]{
              entry.getEntryId(),
              entry.getVehicleNumber(),
              entry.getOwnerName(),
              entry.getSlotId(),
              entry.getEntryDate(),
              entry.getEntryTime(),
              entry.getExitDate(),
              entry.getExitTime(),
              entry.getParkingStatus(),
              entry.getPaymentStatus()
        });
    }
}
    }//GEN-LAST:event_btnCurrentlyParkedActionPerformed

    private void btnSearchSlotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchSlotActionPerformed
       String slotId = JOptionPane.showInputDialog(this, "Enter Slot ID:");

       ParkingEntryFileHandler fileHandler = new ParkingEntryFileHandler();

       ArrayList<ParkingEntry> entryList = fileHandler.loadEntries();

       DefaultTableModel model = (DefaultTableModel) tblEntries.getModel();

       model.setRowCount(0);

       boolean found = false;

       for (ParkingEntry entry : entryList) {

          if (entry.getSlotId().equalsIgnoreCase(slotId)) {

             model.addRow(new Object[]{
             entry.getEntryId(),
             entry.getVehicleNumber(),
             entry.getOwnerName(),
             entry.getSlotId(),
             entry.getEntryDate(),
             entry.getEntryTime(),
             entry.getExitDate(),
             entry.getExitTime(),
             entry.getParkingStatus(),
             entry.getPaymentStatus()
            });

            found = true;
        }
    }

    if (!found) {
        JOptionPane.showMessageDialog(this, "Slot not found.");
    }        
    }//GEN-LAST:event_btnSearchSlotActionPerformed

    private void btnGenerateReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateReportActionPerformed
       ParkingEntryFileHandler fileHandler = new ParkingEntryFileHandler();

       ArrayList<ParkingEntry> entryList = fileHandler.loadEntries();

       int currentlyParked = 0;
       int unpaid = 0;

       for (ParkingEntry entry : entryList) {

          if (entry.getParkingStatus().equalsIgnoreCase("PARKED")) {
          currentlyParked++;
        }

          if (entry.getPaymentStatus().equalsIgnoreCase("UNPAID")) {
          unpaid++;
        }
}

JOptionPane.showMessageDialog(
        this,"Security Monitoring Report\n\n"+ "Currently Parked Vehicles: " + currentlyParked + "\n"+ "Vehicles with Unpaid Parking Fee: " + unpaid
);        
    }//GEN-LAST:event_btnGenerateReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new StaffSecurityGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCurrentlyParked;
    private javax.swing.JButton btnGenerateReport;
    private javax.swing.JButton btnSearchSlot;
    private javax.swing.JButton btnSearchVehicle;
    private javax.swing.JButton btnUnpaidRecords;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JScrollPane scrollEntries;
    private javax.swing.JTable tblEntries;
    // End of variables declaration//GEN-END:variables
}
