/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.java.project.haneen.gui;
import com.mycompany.java.project.haneen.file.StaffFileHandler;
import com.mycompany.java.project.haneen.model.ParkingStaff;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author haneen_almutairi
 */
public class StaffManagementGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StaffManagementGUI.class.getName());

    /**
     * Creates new form StaffManagementGUI
     */
    public StaffManagementGUI() {
        initComponents();
        loadStaffTable();
    }
    
    private void loadStaffTable() {

    StaffFileHandler fileHandler = new StaffFileHandler();

    ArrayList<ParkingStaff> staffList = fileHandler.loadStaff();

    DefaultTableModel model = (DefaultTableModel) tblStaff.getModel();

    model.setRowCount(0);

    for (ParkingStaff staff : staffList) {

        model.addRow(new Object[]{
            staff.getStaffId(),
            staff.getStaffName(),
            staff.getRole(),
            staff.getAssignedGate(),
            staff.getAssignedFloor(),
            staff.getShiftTime(),
            staff.getStaffStatus()
        });
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtStaffId = new javax.swing.JTextField();
        txtStaffName = new javax.swing.JTextField();
        txtShiftTime = new javax.swing.JTextField();
        cmbRole = new javax.swing.JComboBox<>();
        cmbAssignedGate = new javax.swing.JComboBox<>();
        cmbAssignedFloor = new javax.swing.JComboBox<>();
        cmbStaffStatus = new javax.swing.JComboBox<>();
        btnAddStaff = new javax.swing.JButton();
        btnUpdateStaff = new javax.swing.JButton();
        btnDeleteStaff = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        scrollStaff = new javax.swing.JScrollPane();
        tblStaff = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        cmbSearchBy = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txtSearchValue = new javax.swing.JTextField();
        btnSearchStaff = new javax.swing.JButton();
        btnShowAllStaff = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Staff Management System");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setText("Staff Management System");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel2.setText("Staff ID:");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel3.setText("Staff Name:");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel4.setText("Role:");

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel5.setText("Assigned Gate:");

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel6.setText("Assigned Floor:");

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel7.setText("Shift Time:");

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel8.setText("Staff Status:");

        txtStaffId.addActionListener(this::txtStaffIdActionPerformed);

        cmbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Security Officer", "Supervisor", "Manager" }));

        cmbAssignedGate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gate A", "Gate B", "Gate C" }));
        cmbAssignedGate.addActionListener(this::cmbAssignedGateActionPerformed);

        cmbAssignedFloor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Floor 1", "Floor 2", "Floor 3" }));

        cmbStaffStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "On Duty", "Off Duty", "On Leave" }));

        btnAddStaff.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        btnAddStaff.setText("Add Staff");
        btnAddStaff.addActionListener(this::btnAddStaffActionPerformed);

        btnUpdateStaff.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        btnUpdateStaff.setText("Update Staff");
        btnUpdateStaff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateStaffMouseClicked(evt);
            }
        });
        btnUpdateStaff.addActionListener(this::btnUpdateStaffActionPerformed);

        btnDeleteStaff.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        btnDeleteStaff.setText("Delete Staff");
        btnDeleteStaff.addActionListener(this::btnDeleteStaffActionPerformed);

        btnClear.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(this::btnClearActionPerformed);

        tblStaff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Staff ID", "Staff Name", "Role", "Assigned Gate", "Assigned Floor", "Shift Time", "Staff Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblStaff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblStaffMouseClicked(evt);
            }
        });
        scrollStaff.setViewportView(tblStaff);

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel9.setText("Search By:");

        cmbSearchBy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Staff ID", "Staff Name", "Role", "Assigned Gate", "Assigned Floor", "Staff Status" }));

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel10.setText("Search:");

        txtSearchValue.addActionListener(this::txtSearchValueActionPerformed);

        btnSearchStaff.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        btnSearchStaff.setText("Search");
        btnSearchStaff.addActionListener(this::btnSearchStaffActionPerformed);

        btnShowAllStaff.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        btnShowAllStaff.setText("Show All");
        btnShowAllStaff.addActionListener(this::btnShowAllStaffActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(33, 33, 33)
                                                .addComponent(txtStaffName))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(34, 34, 34)
                                                .addComponent(cmbRole, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cmbAssignedGate, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtShiftTime)
                                            .addComponent(cmbAssignedFloor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cmbStaffStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(57, 57, 57)
                                        .addComponent(txtStaffId)))
                                .addGap(84, 84, 84))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(cmbSearchBy, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(txtSearchValue, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSearchStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnShowAllStaff))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(btnAddStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(btnUpdateStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(btnDeleteStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(101, 101, 101))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(scrollStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtStaffId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtStaffName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cmbAssignedGate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cmbAssignedFloor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtShiftTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cmbStaffStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddStaff)
                    .addComponent(btnUpdateStaff)
                    .addComponent(btnDeleteStaff)
                    .addComponent(btnClear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cmbSearchBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtSearchValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchStaff)
                    .addComponent(btnShowAllStaff))
                .addGap(77, 77, 77)
                .addComponent(scrollStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtStaffIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStaffIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStaffIdActionPerformed

    private void cmbAssignedGateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAssignedGateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbAssignedGateActionPerformed

    private void btnDeleteStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteStaffActionPerformed
       int selectedRow = tblStaff.getSelectedRow();

       if (selectedRow == -1) {
           JOptionPane.showMessageDialog(this,"Please select a staff record to delete.");
              return;
    }

       String staffId = tblStaff.getValueAt(selectedRow, 0).toString();

       StaffFileHandler fileHandler = new StaffFileHandler();

       ArrayList<ParkingStaff> staffList = fileHandler.loadStaff();

       boolean deleted = false;

       for (ParkingStaff staff : staffList) {

        if (staff.getStaffId().equalsIgnoreCase(staffId)) {
            staffList.remove(staff);
            deleted = true;
            break;
        }
    }

        if (deleted) {
           fileHandler.saveStaff(staffList);
           loadStaffTable();

        JOptionPane.showMessageDialog(this,"Staff deleted successfully.");
    }        
    }//GEN-LAST:event_btnDeleteStaffActionPerformed

    private void btnAddStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStaffActionPerformed
       String staffId = txtStaffId.getText();
       String staffName = txtStaffName.getText();

       String role = cmbRole.getSelectedItem().toString();
       String assignedGate = cmbAssignedGate.getSelectedItem().toString();
       String assignedFloor = cmbAssignedFloor.getSelectedItem().toString();

       String shiftTime = txtShiftTime.getText();

       String staffStatus = cmbStaffStatus.getSelectedItem().toString();

       if (staffId.trim().isEmpty() || staffName.trim().isEmpty() || shiftTime.trim().isEmpty()) {

           JOptionPane.showMessageDialog(this,"Please fill in all required fields.");

           return;
    }

    StaffFileHandler fileHandler = new StaffFileHandler();

    ArrayList<ParkingStaff> staffList = fileHandler.loadStaff();

    for (ParkingStaff existingStaff : staffList) {

        if (existingStaff.getStaffId().equalsIgnoreCase(staffId)) {

            JOptionPane.showMessageDialog(this,"Staff ID already exists.");

            return;
        }
    }

    ParkingStaff staff = new ParkingStaff(
            staffId,
            staffName,
            role,
            assignedGate,
            assignedFloor,
            shiftTime,
            staffStatus
    );

    staffList.add(staff);

    fileHandler.saveStaff(staffList);

    loadStaffTable();

    txtStaffId.setText("");
    txtStaffName.setText("");
    cmbRole.setSelectedIndex(0);
    cmbAssignedGate.setSelectedIndex(0);
    cmbAssignedFloor.setSelectedIndex(0);
    txtShiftTime.setText("");
    cmbStaffStatus.setSelectedIndex(0);

    JOptionPane.showMessageDialog(this,"Staff added successfully.");
       
    }//GEN-LAST:event_btnAddStaffActionPerformed

    private void txtSearchValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchValueActionPerformed

    private void btnSearchStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchStaffActionPerformed
       String searchBy = cmbSearchBy.getSelectedItem().toString();
       String searchValue = txtSearchValue.getText().trim();

       if (searchValue.isEmpty()) {
           JOptionPane.showMessageDialog(this,"Please enter a search value.");
        return;
    }

       StaffFileHandler fileHandler = new StaffFileHandler();
       ArrayList<ParkingStaff> staffList = fileHandler.loadStaff();

       DefaultTableModel model =
            (DefaultTableModel) tblStaff.getModel();

       model.setRowCount(0);

       boolean found = false;

       for (ParkingStaff staff : staffList) {

          boolean match = false;

           if (searchBy.equals("Staff ID")) {
              match = staff.getStaffId().equalsIgnoreCase(searchValue);

        } 
           else if (searchBy.equals("Staff Name")) {
            match = staff.getStaffName().equalsIgnoreCase(searchValue);

        }
           else if (searchBy.equals("Role")) {
            match = staff.getRole().equalsIgnoreCase(searchValue);

        }
           else if (searchBy.equals("Assigned Gate")) {
            match = staff.getAssignedGate().equalsIgnoreCase(searchValue);

        }
           else if (searchBy.equals("Assigned Floor")) {
            match = staff.getAssignedFloor().equalsIgnoreCase(searchValue);

        }
           else if (searchBy.equals("Staff Status")) {
            match = staff.getStaffStatus().equalsIgnoreCase(searchValue);
        }

        if (match) {

            model.addRow(new Object[]{
                staff.getStaffId(),
                staff.getStaffName(),
                staff.getRole(),
                staff.getAssignedGate(),
                staff.getAssignedFloor(),
                staff.getShiftTime(),
                staff.getStaffStatus()
                    
            });

            found = true;
        }
    }

    if (!found) {
        JOptionPane.showMessageDialog(this, "No staff record found.");
    }        
    
    }//GEN-LAST:event_btnSearchStaffActionPerformed

    private void btnShowAllStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowAllStaffActionPerformed
       loadStaffTable();

       txtSearchValue.setText("");
       cmbSearchBy.setSelectedIndex(0);        
    }//GEN-LAST:event_btnShowAllStaffActionPerformed

    private void btnUpdateStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateStaffActionPerformed
       int selectedRow = tblStaff.getSelectedRow();

       if (selectedRow == -1) {
          JOptionPane.showMessageDialog(this,"Please select a staff record to update.");
           return;
}

       String staffId = txtStaffId.getText().trim();
       String staffName = txtStaffName.getText().trim();
       String role = cmbRole.getSelectedItem().toString();
       String assignedGate = cmbAssignedGate.getSelectedItem().toString();
       String assignedFloor = cmbAssignedFloor.getSelectedItem().toString();
       String shiftTime = txtShiftTime.getText().trim();
       String staffStatus = cmbStaffStatus.getSelectedItem().toString();

       if (staffId.isEmpty() || staffName.isEmpty() || shiftTime.isEmpty()) {
          JOptionPane.showMessageDialog(this,"Please fill in all required fields.");
           return;
}

     StaffFileHandler fileHandler = new StaffFileHandler();
     ArrayList<ParkingStaff> staffList = fileHandler.loadStaff();

     for (ParkingStaff staff : staffList) {

     if (staff.getStaffId().equalsIgnoreCase(staffId)) {

        staff.setStaffName(staffName);
        staff.setRole(role);
        staff.setAssignedGate(assignedGate);
        staff.setAssignedFloor(assignedFloor);
        staff.setShiftTime(shiftTime);
        staff.setStaffStatus(staffStatus);

        break;
    }
}

     fileHandler.saveStaff(staffList);

     loadStaffTable();

     txtStaffId.setText("");
     txtStaffName.setText("");
     cmbRole.setSelectedIndex(0);
     cmbAssignedGate.setSelectedIndex(0);
     cmbAssignedFloor.setSelectedIndex(0);
     txtShiftTime.setText("");
     cmbStaffStatus.setSelectedIndex(0);

     JOptionPane.showMessageDialog(this,"Staff updated successfully.");        
    }//GEN-LAST:event_btnUpdateStaffActionPerformed

    private void btnUpdateStaffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateStaffMouseClicked
             
    }//GEN-LAST:event_btnUpdateStaffMouseClicked

    private void tblStaffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStaffMouseClicked
       int selectedRow = tblStaff.getSelectedRow();

       if (selectedRow == -1) {
         return;
    }

       txtStaffId.setText(tblStaff.getValueAt(selectedRow, 0).toString());
       txtStaffName.setText(tblStaff.getValueAt(selectedRow, 1).toString());
       cmbRole.setSelectedItem(tblStaff.getValueAt(selectedRow, 2).toString());
       cmbAssignedGate.setSelectedItem(tblStaff.getValueAt(selectedRow, 3).toString());
       cmbAssignedFloor.setSelectedItem(tblStaff.getValueAt(selectedRow, 4).toString());
       txtShiftTime.setText(tblStaff.getValueAt(selectedRow, 5).toString());
       cmbStaffStatus.setSelectedItem(tblStaff.getValueAt(selectedRow, 6).toString());

       txtStaffId.setEditable(false);   
    }//GEN-LAST:event_tblStaffMouseClicked

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
       txtStaffId.setText("");
       txtStaffName.setText("");
       cmbRole.setSelectedIndex(0);
       cmbAssignedGate.setSelectedIndex(0);
       cmbAssignedFloor.setSelectedIndex(0);
       txtShiftTime.setText("");
       cmbStaffStatus.setSelectedIndex(0);

       txtStaffId.setEditable(true);

       tblStaff.clearSelection();    
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new StaffManagementGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddStaff;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDeleteStaff;
    private javax.swing.JButton btnSearchStaff;
    private javax.swing.JButton btnShowAllStaff;
    private javax.swing.JButton btnUpdateStaff;
    private javax.swing.JComboBox<String> cmbAssignedFloor;
    private javax.swing.JComboBox<String> cmbAssignedGate;
    private javax.swing.JComboBox<String> cmbRole;
    private javax.swing.JComboBox<String> cmbSearchBy;
    private javax.swing.JComboBox<String> cmbStaffStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane scrollStaff;
    private javax.swing.JTable tblStaff;
    private javax.swing.JTextField txtSearchValue;
    private javax.swing.JTextField txtShiftTime;
    private javax.swing.JTextField txtStaffId;
    private javax.swing.JTextField txtStaffName;
    // End of variables declaration//GEN-END:variables
}
